sonar.projectKey=FirmansyahDzakwanArifien_FinalProject_PW2_Topik7_a4411026-d8c7-4a00-bb23-35bffe464305
sonar.projectName=FinalProject_PW2_Topik7
sonar.sources=app,routes,database
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/**,tests/**
sonar.php.version=8.2
